#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get the list of staged files
staged_files=$(git diff --name-only --cached)

# If there are no staged files, exit early
if [ -z "$staged_files" ]; then
  echo "No staged files to format."
  exit 0
fi

# Run Prettier to format the staged files
npx prettier --write "$staged_files"

# Check if there are any changes after running Prettier
if [ -n "$(git diff --name-only --cached)" ]; then
  # Stage the changes
  git add .

  # Amend the previous commit without changing the commit message
  git commit --amend --no-edit
fi
